name: generator
description: Auto Nong index generator.
version: 1.0.0

environment:
  sdk: ^3.4.3

dependencies:
  http: ^1.2.2
  uuid: ^4.4.2
  # path: ^1.8.0

dev_dependencies:
  lints: ">=3.0.0 <6.0.0"
  test: ^1.24.0
